# Generated by AI (GitHub Copilot)
"""
IDE Protocol for SARA (Gen1)
- Provides automation, validation, and integration hooks for IDEs (VS Code, PyCharm, etc.)
- Extensible for editor commands, file operations, and code intelligence
- Routed through control/mama for enforcement and session management
"""
import os
import json
from typing import Any, Dict

class IDEProtocol:
    def __init__(self, config_path: str = None):
        self.config_path = config_path or "ide_protocol_config.json"
        self.state = self._load_state()

    def _load_state(self) -> Dict[str, Any]:
        if os.path.exists(self.config_path):
            with open(self.config_path, "r", encoding="utf-8") as f:
                return json.load(f)
        return {}

    def _save_state(self):
        with open(self.config_path, "w", encoding="utf-8") as f:
            json.dump(self.state, f, indent=2)

    def handle_command(self, command: str, args: Dict[str, Any]) -> Dict[str, Any]:
        """Main entry point for IDE protocol actions.
        Supports diagnostics/improvement mode, IDE launch, process control, and research window."""
        if command == "list_files":
            return self.list_files(args.get("directory", "."))
        elif command == "open_file":
            return self.open_file(args.get("file_path"))
        elif command == "run_code_action":
            return self.run_code_action(args.get("action"), args.get("file_path"))
        elif command == "diagnostics_mode":
            return self.diagnostics_mode(args)
        elif command == "launch_research_window":
            return self.launch_research_window(args.get("url"))
        return {"status": "error", "error": f"Unknown command: {command}"}

    def diagnostics_mode(self, args: Dict[str, Any]) -> Dict[str, Any]:
        """Launch preferred IDE (VS Code), stop all processes for this environment unless 'launch research window' is specified."""
        import subprocess
        import signal
        preferred_ide = args.get("ide", "code")  # Default to VS Code
        research_mode = args.get("research", False)
        # Stop all processes for this environment (placeholder: user should implement actual logic)
        if not research_mode:
            # This is a placeholder for stopping processes; user should implement environment-specific logic
            # Example: os.system('taskkill /F /IM python.exe')
            pass
        # Launch VS Code (or preferred IDE)
        try:
            subprocess.Popen([preferred_ide])
            return {"status": "ok", "message": f"Launched {preferred_ide} in diagnostics/improvement mode."}
        except Exception as e:
            return {"status": "error", "error": f"Failed to launch {preferred_ide}: {e}"}

    def launch_research_window(self, url: str) -> Dict[str, Any]:
        """Launch a web page window for research."""
        import webbrowser
        try:
            webbrowser.open(url)
            return {"status": "ok", "message": f"Launched research window: {url}"}
        except Exception as e:
            return {"status": "error", "error": f"Failed to launch research window: {e}"}

    def list_files(self, directory: str) -> Dict[str, Any]:
        try:
            files = os.listdir(directory)
            return {"status": "ok", "files": files}
        except Exception as e:
            return {"status": "error", "error": str(e)}

    def open_file(self, file_path: str) -> Dict[str, Any]:
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()
            return {"status": "ok", "content": content}
        except Exception as e:
            return {"status": "error", "error": str(e)}

    def run_code_action(self, action: str, file_path: str) -> Dict[str, Any]:
        # Placeholder for code actions (format, lint, refactor, etc.)
        # Extend with actual integrations as needed
        return {"status": "ok", "message": f"Ran action '{action}' on {file_path}"}

# Protocol registration for dispatcher
ide_protocol = IDEProtocol()

def dispatch_ide_protocol(command: str, args: Dict[str, Any]) -> Dict[str, Any]:
    return ide_protocol.handle_command(command, args)
