~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~ HEADER (strict, machine-verified)                        ~
~ kennel=                                                  ~
~ generation=                                              ~
~ evolution=                                               ~
~ version=                                                 ~
~ date=                                                    ~
~ location=                                                ~
~ language=                                                ~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@ Trainers (semantic imports)  capability modules @
call sara_core
call sara_security
call sara_mama
call sara_sdk
@ All trainers must appear directly under the header.
@ Trainers seed Flood-Search and Tagger for capability routing.
@ Puppy defines primitive shapes, types, and Sequians @

<puppy_name> Puppy%(puppy_type)%

@ Sequian usage pattern (defined in Puppy.slam) @
# sequian <name> %(parameters)% gives(result_type)%
@ Dog uses Sequians, layers, or CartiGene states to perform behavior @

<dog_name> does $(
    sequian_1,
    sequian_2,
    layer_or_math_unit
)$
for %( condition OR number_of_times )%
using( nexusdata OR puppy_cartigini )
gives( result_type )%
@ Structured containers for type flow @

<input>  Breed%( InputType )
<process> Breed%( ProcessType )
<output> Breed%( OutputType )
(sara_core.sara_isa_audio_card)
    connection( sara_control.layer12_acoustic_physics )
|DogShowName_| kennel %(
    InputBreed,
    ProcessBreed,
    OutputBreed
) connect(
    route1,
    route2,
    route3
)
@ DogShow = public interface
@ Kennel = module container
@ connect() = Sequian / CartiGene / layer routing
<AXIS_BLOCK>
# Auto-generated by IDE.
# Each syntax element defined above may include a translation axis:
#
# axis:<name>
#     sara: <syntax>
#     python: <lowered_form>
#     c: <lowered_form>
#     rust: <lowered_form>
#
# Input axes, connection axes, output axes.
</AXIS_BLOCK>
<FOOTER>
# output_type=
# target_language=
# constraints=
</FOOTER>
~TAGGER_MIRROR~
#@REGISTRY_MIRROR@#