# Generated by AI (GitHub Copilot)
"""
Minimal Tkinter UI for SARA Protocol Actions
- Calls MamaDispatcher for protocol actions
- Lists contacts and displays results/errors
"""
import tkinter as tk
from tkinter import messagebox, simpledialog, scrolledtext
import json
import os

# Import MamaDispatcher (assumes sara_mamagen1.py is in the same directory)
try:
    from sara_mamagen1 import MamaDispatcher
except ImportError:
    MamaDispatcher = None

class SARAUI(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("SARA Mama UI")
        self.geometry("500x400")
        self.dispatcher = MamaDispatcher() if MamaDispatcher else None
        self.create_widgets()

    def create_widgets(self):
        # Protocol action buttons
        actions = [
            ("Word", self.word_action),
            ("Excel", self.excel_action),
            ("Email", self.email_action),
            ("Call", self.call_action),
            ("Contacts", self.contacts_action),
        ]
        for i, (label, cmd) in enumerate(actions):
            tk.Button(self, text=label, width=12, command=cmd).grid(row=0, column=i, padx=5, pady=10)

        # Output area
        self.output = scrolledtext.ScrolledText(self, width=60, height=18, state='disabled')
        self.output.grid(row=1, column=0, columnspan=5, padx=10, pady=10)

    def show_output(self, text):
        self.output.config(state='normal')
        self.output.delete(1.0, tk.END)
        self.output.insert(tk.END, text)
        self.output.config(state='disabled')

    def word_action(self):
        filename = simpledialog.askstring("Word", "Enter Word file path:")
        if filename:
            result = self.dispatch('word', {'file': filename})
            self.show_output(result)

    def excel_action(self):
        filename = simpledialog.askstring("Excel", "Enter Excel file path:")
        if filename:
            result = self.dispatch('excel', {'file': filename})
            self.show_output(result)

    def email_action(self):
        email = simpledialog.askstring("Email", "Enter email address:")
        if email:
            result = self.dispatch('email', {'email': email})
            self.show_output(result)

    def call_action(self):
        number = simpledialog.askstring("Call", "Enter phone/VoIP number:")
        if number:
            result = self.dispatch('call', {'number': number})
            self.show_output(result)

    def contacts_action(self):
        result = self.dispatch('contacts', {})
        self.show_output(result)

    def dispatch(self, action, params):
        if not self.dispatcher:
            return "MamaDispatcher not found. Please ensure sara_mamagen1.py is present."
        try:
            # The dispatcher should have a method like: dispatch(action, params)
            response = self.dispatcher.dispatch(action, params)
            return json.dumps(response, indent=2) if not isinstance(response, str) else response
        except Exception as e:
            return f"Error: {e}"

if __name__ == "__main__":
    app = SARAUI()
    app.mainloop()
