# shunt header: sara_security_gen1
# --- FDSSM FORMALIZATION (AUTOGENERATED) ---
from typing import Dict, Any

# ShuntFSM object declaration (stub)
class ShuntFSM:
    def __init__(self, states: Dict[str, int], transitions: Dict[str, Any]):
        self.states = states
        self.transitions = transitions

# FSM state and transition table (stub/example)
SECURITY_FSM_STATES = {
    "idle": 0,
    "processing": 1,
    "done": 2,
    "error": 3
}
SECURITY_FSM_TRANSITIONS = {
    (0, "start"): (1, "begin_processing"),
    (1, "finish"): (2, "complete"),
    (1, "fail"): (3, "handle_error"),
    (3, "reset"): (0, "reset_idle")
}
security_fsm = ShuntFSM(SECURITY_FSM_STATES, SECURITY_FSM_TRANSITIONS)

# Shunt entrypoint
def security_shunt_entrypoint(command: str, payload: dict) -> dict:
    """
    Single entrypoint for all cross-pillar actions. Applies header validation and routes to FSM.
    """
    if not validate_shunt_header(payload):
        return {"success": False, "error": "Invalid shunt header"}

    # ACT-based dispatch logic (stub: no SECURITY codes in actionmap.json)
    act_map = {
        "00": (audit_gate, "RETURN"),
        "01": (quarantine, "RETURN"),
        "10": (scan, "RETURN"),
        "11": (noop_action, "RETURN")
    }
    act_code = str(payload.get("ACT", "")).zfill(2)
    if act_code not in act_map:
        return {"success": False, "error": f"Unknown ACT code: {act_code}"}
    fn, out_route = act_map[act_code]
    try:
        result = fn(payload)  # pass full shunt envelope so ACT functions can access context
    except Exception as e:
        return {"success": False, "error": f"Dispatch error: {e}", "action_code": act_code, "function": fn.__name__, "out_route": out_route}
    return {"success": True, "action_code": act_code, "function": fn.__name__, "out_route": out_route, "result": result}

# --- ACT-mapped functions for SECURITY pillar ---
def audit_gate(envelope: dict) -> dict:
    """ACT 00 — Real allow/deny/challenge decision using trust policy and STABLES."""
    inner = dict(envelope.get("payload", {}))
    context_tags = list(envelope.get("context_tags", []))
    # Extract environment and session context from envelope
    environment = str(inner.get("environment") or "local_only")
    host = str(inner.get("host") or "localhost")
    session_id = str(envelope.get("shunt_id") or inner.get("session_id") or "")
    # Check trust posture (scout_house_posture_sec may not be defined yet — use policy check directly)
    policy = _load_trust_policy_sec()
    allowed_env = {str(v).strip().lower() for v in (policy.get("allowed_environments") or [])}
    trusted_hosts = {str(v).strip().lower() for v in (policy.get("trusted_hosts") or [])}
    env_ok = environment.lower() in allowed_env
    host_ok = host.lower() in trusted_hosts
    # STABLES validation if session context present
    stables_result = {}
    if session_id or any(t in {"vnce", "envoy", "session"} for t in context_tags):
        stables_result = stables_validate_session_sec(
            shunt_envelope=envelope,
            context={"session_id": session_id, "environment": environment, "host": host},
        )
        stables_outcome = stables_result.get("outcome", SECURITY_OUTCOME_ALLOW)
        if stables_outcome in {SECURITY_OUTCOME_QUARANTINE, SECURITY_OUTCOME_LOCKDOWN}:
            return {"outcome": stables_outcome, "reason": stables_result.get("reason", "STABLES:deny"),
                    "stables": stables_result, "audit_gate": True}
        if stables_outcome == SECURITY_OUTCOME_CHALLENGE:
            return {"outcome": SECURITY_OUTCOME_CHALLENGE, "reason": stables_result.get("reason", "STABLES:challenge"),
                    "stables": stables_result, "audit_gate": True}
    if not env_ok or not host_ok:
        _SECURITY_KEEP_STATE["last_outcome"] = SECURITY_OUTCOME_CHALLENGE
        return {"outcome": SECURITY_OUTCOME_CHALLENGE, "reason": "AUDIT_GATE:env/host not trusted",
                "environment": environment, "host": host, "stables": stables_result, "audit_gate": True}
    _SECURITY_KEEP_STATE["last_outcome"] = SECURITY_OUTCOME_ALLOW
    return {"outcome": SECURITY_OUTCOME_ALLOW, "reason": "AUDIT_GATE:pass",
            "environment": environment, "host": host, "stables": stables_result, "audit_gate": True}

def quarantine(envelope: dict) -> dict:
    """ACT 01 — Quarantine the shunt envelope; log to incident history and return QUARANTINE outcome."""
    import datetime as _dt
    record = {
        "ts": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "shunt_id": envelope.get("shunt_id", ""),
        "source_pillar": envelope.get("source_pillar", "UNKNOWN"),
        "intent": envelope.get("intent", ""),
        "context_tags": list(envelope.get("context_tags", [])),
        "reason": "QUARANTINE:ACT01",
        "outcome": SECURITY_OUTCOME_QUARANTINE,
    }
    _SECURITY_KEEP_STATE.setdefault("incident_history", []).append(record)
    _SECURITY_KEEP_STATE["last_outcome"] = SECURITY_OUTCOME_QUARANTINE
    # Write to audit log file if possible
    try:
        _logs_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "logs")
        os.makedirs(_logs_dir, exist_ok=True)
        _log_path = os.path.join(_logs_dir, "security_quarantine_log.ndjson")
        with open(_log_path, "a", encoding="utf-8") as f:
            import json as _json
            f.write(_json.dumps(record) + "\n")
    except Exception:
        pass
    return {"outcome": SECURITY_OUTCOME_QUARANTINE, "record": record, "quarantine": True}

def scan(envelope: dict) -> dict:
    """ACT 10 — Threat scan: check payload for known threat indicators."""
    inner = dict(envelope.get("payload", {}))
    threat_patterns = ["exec(", "eval(", "__import__", "subprocess", "os.system", "rm -rf", "DROP TABLE", "SELECT * FROM"]
    # Scan the string representation of the inner payload
    try:
        import json as _json
        payload_str = _json.dumps(inner)
    except Exception:
        payload_str = str(inner)
    threats_found = [p for p in threat_patterns if p.lower() in payload_str.lower()]
    if threats_found:
        _SECURITY_KEEP_STATE["last_outcome"] = SECURITY_OUTCOME_QUARANTINE
        return {"outcome": SECURITY_OUTCOME_QUARANTINE, "threats": threats_found,
                "reason": "SCAN:threat_pattern_detected", "scan": True}
    _SECURITY_KEEP_STATE["last_outcome"] = SECURITY_OUTCOME_ALLOW
    return {"outcome": SECURITY_OUTCOME_ALLOW, "threats": [], "reason": "SCAN:clean", "scan": True}

def noop_action(envelope: dict) -> dict:
    """ACT 11 — No operation; returns envelope metadata."""
    return {"success": True, "noop": True, "shunt_id": envelope.get("shunt_id", "")}

# Header enforcement wrapper
def validate_shunt_header(payload: dict) -> bool:
    """
    Enforces shunt header contract on inbound/outbound actions.
    """
    required_fields = ["shunt_id", "source_pillar", "target_pillar", "timestamp", "intent", "payload", "context_tags", "requires_response"]
    return all(field in payload for field in required_fields)
SARA_SECURITY_HEADER_START = "SARA_SECURITY_HEADER_START"
SARA_SECURITY_HEADER_BYTE0 = 0x01
SARA_SECURITY_HEADER_BYTE1 = 0x2E
SARA_SECURITY_HEADER_BYTE2 = 0x01
SARA_SECURITY_HEADER_BYTE3 = 0xE2
SARA_SECURITY_HEADER_BYTE4 = 0xC0
SARA_SECURITY_HEADER_BYTE5 = 0x71
SARA_SECURITY_HEADER_RESERVED_BYTES = 210
SARA_SECURITY_HEADER_END = "SARA_SECURITY_HEADER_END"
SARA_SECURITY_BINARY_SPECIAL_HEADER_LITERAL = """SARA_SECURITY_HEADER_START
BYTE0: 01        # Shunt Mode Enable
BYTE1: 2E        # Domain=00 CPU | Origin=10 Security-native | Authority=11 SECURITY-only | Routing=10 audit mesh
BYTE2: 01        # Envoy/Resonator Switch (1 = security inspects as special path)
BYTE3: E2        # FileName_FirstLetter=11 | ThreatPattern=10 | Lane=10
BYTE4: C0        # ExtensionSignature=11 | DomainConfirm=00
BYTE5: 71        # ShuntAuthority=7 quarantine/audit | ShuntLock=1 sealed
RESERVED: 00 * 210 bytes
SARA_SECURITY_HEADER_END"""
SARA_SECURITY_BINARY_SPECIAL_HEADER_BYTES = bytes(
    [
        SARA_SECURITY_HEADER_BYTE0,
        SARA_SECURITY_HEADER_BYTE1,
        SARA_SECURITY_HEADER_BYTE2,
        SARA_SECURITY_HEADER_BYTE3,
        SARA_SECURITY_HEADER_BYTE4,
        SARA_SECURITY_HEADER_BYTE5,
    ]
)
# BuceyShunt direct-communication header
# protocol lane: Text -> Binary
# role: security gate/audit pillar for NBS project shunting method
# =========================================================
# Kingdome Phoenix Protocol Integration (Security Side)
# NBS Project Security Pillar -- gate, audit, scan, and quarantine surface.
# =========================================================
# pillar: sara_security
# generation: gen0-harness-shim
# frozen reference: sara_security.py (2024-06-10) -- do not import directly; see note below
#
# Purpose:
#   Provide the NBS project security layer for Gen1.
#   sara_security.py is a complete Gen0 monolith (frozen). It carries heavy
#   external dependencies (cv2, numpy, requests) that are not required here.
#   This file is the harness-compatible security face used for sovereignty
#   checks, audit, file scanning, threat evaluation, and quarantine handling.
#
# Harness path this file defines:
#   1. king_sovereignty_check  -- sovereign lane clear before any gate opens
#   2. paladin_gate            -- allow/deny decision on the incoming request
#   3. sheriff_audit           -- structured audit event written for the record
#   4. dispatch_security       -- control-routed security command surface
#   5. office/image audits     -- document scan and quarantine path
#
# SPEC NOTE (language ownership):
# - sara_core remains Python.
# - sara_control target language is C.
# - sara_security target language is Ada.
# This is a planning note only and does not change runtime behavior.
# Literal binary special header preserved at module top in:
# - SARA_SECURITY_HEADER_START / SARA_SECURITY_HEADER_END
# - SARA_SECURITY_HEADER_BYTE0..SARA_SECURITY_HEADER_BYTE5
# - SARA_SECURITY_HEADER_RESERVED_BYTES
# - SARA_SECURITY_BINARY_SPECIAL_HEADER_LITERAL
# - SARA_SECURITY_BINARY_SPECIAL_HEADER_BYTES

import os
import json
import glob
import shutil
import hashlib
import subprocess
import importlib
import re
from datetime import datetime, timezone
from typing import Optional, Dict, List, Any

# ===========================================================================
# SOVEREIGNTY CHECK (King lane -- observer only from Control perspective)
# ===========================================================================
ROYAL_SIGNET = "USER_AUTH_CONFIRMED"
SECURITY_OUTCOME_ALLOW = "ALLOW"
SECURITY_OUTCOME_CHALLENGE = "CHALLENGE"
SECURITY_OUTCOME_QUARANTINE = "QUARANTINE"
SECURITY_OUTCOME_LOCKDOWN = "LOCKDOWN"
SECURITY_OUTCOME_ZEROIZE_SAFE = "ZEROIZE_SAFE"
SECURITY_CMD_SCAN_VNCE_ENVOY: str = "scan_vnce_envoy"
SECURITY_CMD_ATTEST_VNCE_SESSION: str = "attest_vnce_session"
SECURITY_CMD_TRUST_POSTURE: str = "trust_posture"
SECURITY_CMD_EVALUATE_SOVEREIGNTY: str = "evaluate_sovereignty"
SECURITY_CMD_VAULT_LIFECYCLE: str = "vault_lifecycle"
SECURITY_CMD_INCIDENT_LIFECYCLE: str = "incident_lifecycle"
SECURITY_CMD_SAFE_ZEROIZE: str = "safe_zeroize"
STABLES_CMD_INIT_SESSION: str = "stables_init_session"
STABLES_CMD_VALIDATE_SESSION: str = "stables_validate_session"
STABLES_CMD_MARK_SESSION_DROP: str = "stables_mark_session_drop"
STABLES_CMD_RESUME_SESSION: str = "stables_resume_session"
STABLES_CMD_CLOSE_SESSION: str = "stables_close_session"
STABLES_ROTATION_WINDOW_SECONDS = 300
STABLES_RESUME_WINDOW_SECONDS = 1800
STABLES_ABANDON_TIMEOUT_SECONDS = 7 * 24 * 60 * 60

# --- VNCE / Envoy protocol constants ---
ENVOY_PROTOCOL_VNCE: str = "vnce"

_SECURITY_KEEP_STATE: Dict[str, Any] = {
    "vault_state": "sealed",
    "control_lockdown": False,
    "last_outcome": SECURITY_OUTCOME_ALLOW,
    "volatile_cache": {},
    "pending_challenges": [],
    "incident_history": [],
    "posture": {},
    "stables_sessions": {},
    "trust_policy": {},
    "vnce_last_attested": {},
}

_TRUST_POLICY_PATHS: List[str] = [
    "/etc/sara-lite/trust-policy.json",
    os.path.join(os.path.dirname(__file__), "trust-policy.json"),
]


def _default_trust_policy_sec() -> Dict[str, Any]:
    return {
        "allowed_environments": ["local", "local_only", "trusted_local", "interactive", "night_shift", "lan", "internet_strict"],
        "trusted_hosts": ["localhost", "127.0.0.1", "::1", "local_only"],
        "allow_lan": True,
        "allow_internet_strict": False,
    }


def _load_trust_policy_sec() -> Dict[str, Any]:
    cached = _SECURITY_KEEP_STATE.get("trust_policy")
    if isinstance(cached, dict) and cached:
        return cached

    policy = _default_trust_policy_sec()
    for path in _TRUST_POLICY_PATHS:
        if not os.path.exists(path):
            continue
        try:
            with open(path, "r", encoding="utf-8") as f:
                loaded = json.load(f)
            if isinstance(loaded, dict):
                policy.update(loaded)
                break
        except Exception:
            continue

    _SECURITY_KEEP_STATE["trust_policy"] = policy
    return policy


def _iso_now_sec() -> str:
    return datetime.now(timezone.utc).isoformat()


def _json_safe_sec(value: Any) -> Any:
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if isinstance(value, dict):
        return {str(k): _json_safe_sec(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_json_safe_sec(v) for v in value]
    return str(value)


def _stables_now_ts_sec() -> int:
    return int(datetime.now(timezone.utc).timestamp())


def _get_stables_sessions_sec() -> Dict[str, Dict[str, Any]]:
    sessions = _SECURITY_KEEP_STATE.get("stables_sessions")
    if not isinstance(sessions, dict):
        sessions = {}
        _SECURITY_KEEP_STATE["stables_sessions"] = sessions
    return sessions


def _stables_extract_context_sec(
    shunt_envelope: Optional[Dict[str, Any]] = None,
    amip_request: Optional[Dict[str, Any]] = None,
    context: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    envelope = dict(shunt_envelope or {})
    request = dict(amip_request or envelope.get("amip_payload") or {})
    context_block = dict(context or {})
    header = envelope.get("header") if isinstance(envelope.get("header"), dict) else {}
    payload = request.get("payload") if isinstance(request.get("payload"), dict) else {}
    machine_profile = request.get("machine_profile") if isinstance(request.get("machine_profile"), dict) else {}
    context_tags = [str(tag).strip().lower() for tag in (envelope.get("context_tags") or []) if tag is not None]
    routing_intent = str(request.get("routing_intent") or envelope.get("intent") or context_block.get("routing_intent") or "").strip().lower()
    workflow_lane = str(
        payload.get("workflow_lane")
        or request.get("workflow_lane")
        or context_block.get("workflow_lane")
        or payload.get("protocol")
        or context_block.get("protocol")
        or ""
    ).strip().lower()
    is_vnce = workflow_lane == "vnce" or "vnce" in routing_intent or payload.get("protocol") == ENVOY_PROTOCOL_VNCE
    is_envoy = bool(payload.get("envoy_mode") or context_block.get("envoy_mode") or any(tag in {"envoy", "vnce"} for tag in context_tags))
    applies = bool(context_block.get("stables_enabled") or payload.get("stables_enabled") or is_vnce or is_envoy)
    session_id = str(
        context_block.get("session_id")
        or payload.get("session_id")
        or envelope.get("request_id")
        or request.get("correlation_id")
        or ""
    ).strip()
    device_identity = str(
        context_block.get("device_identity")
        or context_block.get("device_fingerprint")
        or payload.get("device_identity")
        or payload.get("device_fingerprint")
        or machine_profile.get("profile_id")
        or machine_profile.get("ami_id")
        or envelope.get("ami_id")
        or "local_device"
    ).strip() or "local_device"
    envoy_instance_id = str(
        context_block.get("envoy_instance_id")
        or payload.get("envoy_instance_id")
        or payload.get("envoy_id")
        or header.get("shunt_id")
        or envelope.get("shunt_id")
        or "local_envoy"
    ).strip() or "local_envoy"
    presented_token = str(
        context_block.get("stables_token")
        or context_block.get("presented_token")
        or payload.get("stables_token")
        or payload.get("rotation_token")
        or envelope.get("stables_token")
        or ""
    ).strip()
    hard_enforcement = bool(
        context_block.get("stables_required")
        or payload.get("stables_required")
        or payload.get("rotation_required")
    )
    resume_requested = bool(
        context_block.get("resume_requested")
        or payload.get("resume_requested")
        or payload.get("session_resume")
    )
    session_key = "|".join([session_id or "unknown_session", device_identity, envoy_instance_id])
    return {
        "applies": applies,
        "session_id": session_id,
        "device_identity": device_identity,
        "envoy_instance_id": envoy_instance_id,
        "routing_intent": routing_intent,
        "workflow_lane": workflow_lane or ("vnce" if is_vnce else "control"),
        "presented_token": presented_token,
        "hard_enforcement": hard_enforcement,
        "resume_requested": resume_requested,
        "session_key": session_key,
        "context_tags": context_tags,
    }


def _stables_issue_token_sec(record: Dict[str, Any], presented_token: str = "", now_ts: Optional[int] = None) -> str:
    """Advance STABLES into ACTIVE_ROTATION deterministically without generating or modifying secrets."""
    now_ts = int(now_ts or _stables_now_ts_sec())
    record["current_window"] = now_ts // STABLES_ROTATION_WINDOW_SECONDS
    if str(presented_token or "").strip():
        record["current_token"] = str(presented_token).strip()
    else:
        record["current_token"] = str(record.get("current_token") or "")
    record["state"] = "ACTIVE_ROTATION"
    record["rotation_paused"] = False
    record["last_rotated_at"] = _iso_now_sec()
    record["window_expires_at"] = datetime.fromtimestamp(now_ts + STABLES_ROTATION_WINDOW_SECONDS, timezone.utc).isoformat()
    return str(record.get("current_token") or "")

def _stables_metadata_from_record_sec(record: Dict[str, Any], outcome: str = SECURITY_OUTCOME_ALLOW, reason: str = "STABLES:ok") -> Dict[str, Any]:
    state = str(record.get("state", "CLOSED") or "CLOSED")
    return {
        "applied": True,
        "outcome": outcome,
        "reason": reason,
        "session_id": str(record.get("session_id", "")),
        "device_identity": str(record.get("device_identity", "")),
        "envoy_instance_id": str(record.get("envoy_instance_id", "")),
        "hardness_state": state,
        "rotation_window_status": "paused" if record.get("rotation_paused") else ("inactive" if state == "CLOSED" else "active"),
        "last_verified_at": record.get("last_verified_at"),
        "last_rotated_at": record.get("last_rotated_at"),
        "window_expires_at": record.get("window_expires_at"),
        "resume_window_expires_at": record.get("resume_window_expires_at"),
        "challenge_required": outcome == SECURITY_OUTCOME_CHALLENGE,
        "pending_resume": bool(record.get("pending_resume_token")),
    }

def stables_init_session_sec(
    shunt_envelope: Optional[Dict[str, Any]] = None,
    amip_request: Optional[Dict[str, Any]] = None,
    context: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    context_info = _stables_extract_context_sec(shunt_envelope=shunt_envelope, amip_request=amip_request, context=context)
    if not context_info.get("applies"):
        return {
            "applied": False,
            "outcome": SECURITY_OUTCOME_ALLOW,
            "reason": "STABLES:not-applicable",
            "hardness_state": "CLOSED",
            "rotation_window_status": "inactive",
            "challenge_required": False,
        }

    sessions = _get_stables_sessions_sec()
    session_key = context_info["session_key"]
    record = sessions.get(session_key)
    if not isinstance(record, dict):
        record = {
            "session_id": context_info["session_id"],
            "device_identity": context_info["device_identity"],
            "envoy_instance_id": context_info["envoy_instance_id"],
            "created_at": _iso_now_sec(),
            "created_at_epoch": _stables_now_ts_sec(),
            "state": "INIT",
            "rotation_paused": False,
            "current_token": "",
            "pending_resume_token": None,
            "resume_window_expires_at": None,
            "last_verified_at": None,
        }
        sessions[session_key] = record

    for key in ("session_id", "device_identity", "envoy_instance_id"):
        record[key] = context_info.get(key) or record.get(key)
    record["state"] = "INIT"
    _stables_issue_token_sec(record, presented_token=context_info.get("presented_token", ""))
    return _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_ALLOW, reason="STABLES:init-active")

def stables_mark_session_drop_sec(
    shunt_envelope: Optional[Dict[str, Any]] = None,
    amip_request: Optional[Dict[str, Any]] = None,
    context: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    context_info = _stables_extract_context_sec(shunt_envelope=shunt_envelope, amip_request=amip_request, context=context)
    init_result = stables_init_session_sec(shunt_envelope=shunt_envelope, amip_request=amip_request, context=context)
    if not init_result.get("applied"):
        return init_result
    sessions = _get_stables_sessions_sec()
    record = sessions.get(context_info["session_key"], {})
    record["state"] = "AWAIT_RESUME"
    record["rotation_paused"] = True
    record["pending_resume_token"] = context_info.get("presented_token") or record.get("current_token") or ""
    record["resume_window_expires_at"] = datetime.fromtimestamp(_stables_now_ts_sec() + STABLES_RESUME_WINDOW_SECONDS, timezone.utc).isoformat()
    return _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_CHALLENGE, reason="STABLES:await-resume")

def stables_close_session_sec(
    shunt_envelope: Optional[Dict[str, Any]] = None,
    amip_request: Optional[Dict[str, Any]] = None,
    context: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    context_info = _stables_extract_context_sec(shunt_envelope=shunt_envelope, amip_request=amip_request, context=context)
    if not context_info.get("applies"):
        return {
            "applied": False,
            "outcome": SECURITY_OUTCOME_ALLOW,
            "reason": "STABLES:not-applicable",
            "hardness_state": "CLOSED",
            "rotation_window_status": "inactive",
        }
    sessions = _get_stables_sessions_sec()
    record = sessions.get(context_info["session_key"], {
        "session_id": context_info["session_id"],
        "device_identity": context_info["device_identity"],
        "envoy_instance_id": context_info["envoy_instance_id"],
        "created_at": _iso_now_sec(),
    })
    record["state"] = "CLOSED"
    record["rotation_paused"] = True
    record["current_token"] = None
    record["pending_resume_token"] = None
    record["resume_window_expires_at"] = None
    record["closed_at"] = _iso_now_sec()
    sessions.pop(context_info["session_key"], None)
    return _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_ALLOW, reason="STABLES:closed")


def stables_validate_session_sec(
    shunt_envelope: Optional[Dict[str, Any]] = None,
    amip_request: Optional[Dict[str, Any]] = None,
    context: Optional[Dict[str, Any]] = None,
    metadata_only: bool = False,
) -> Dict[str, Any]:
    context_info = _stables_extract_context_sec(shunt_envelope=shunt_envelope, amip_request=amip_request, context=context)
    if not context_info.get("applies"):
        return {
            "applied": False,
            "outcome": SECURITY_OUTCOME_ALLOW,
            "reason": "STABLES:not-applicable",
            "hardness_state": "CLOSED",
            "rotation_window_status": "inactive",
            "challenge_required": False,
        }

    sessions = _get_stables_sessions_sec()
    session_key = context_info["session_key"]
    record = sessions.get(session_key)
    if not isinstance(record, dict):
        init_result = stables_init_session_sec(shunt_envelope=shunt_envelope, amip_request=amip_request, context=context)
        record = sessions.get(session_key, {})
        if context_info.get("resume_requested"):
            init_result.update({
                "outcome": SECURITY_OUTCOME_CHALLENGE,
                "reason": "STABLES:resume-needs-existing-session",
                "challenge_required": True,
                "recommended_action": "start_new_session",
            })
            return init_result
        return init_result

    now_ts = _stables_now_ts_sec()
    created_epoch = int(record.get("created_at_epoch", now_ts) or now_ts)
    if now_ts - created_epoch >= STABLES_ABANDON_TIMEOUT_SECONDS and record.get("state") in {"AWAIT_RESUME", "EXPIRED"}:
        record["state"] = "ABANDONED"
        record["rotation_paused"] = True
        record["current_token"] = ""
        record["pending_resume_token"] = None
        record["resume_window_expires_at"] = None
        metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_CHALLENGE, reason="STABLES:abandoned-human-verification-required")
        metadata["recommended_action"] = "initiate_new_session_after_human_verification"
        return metadata

    if record.get("state") == "INIT":
        _stables_issue_token_sec(record, presented_token=context_info.get("presented_token", ""), now_ts=now_ts)

    presented_token = context_info.get("presented_token", "")
    if record.get("state") == "AWAIT_RESUME":
        resume_expires_at = record.get("resume_window_expires_at")
        if resume_expires_at:
            try:
                resume_expired = datetime.fromisoformat(str(resume_expires_at)) <= datetime.now(timezone.utc)
            except Exception:
                resume_expired = True
        else:
            resume_expired = True

        if resume_expired:
            record["state"] = "EXPIRED"
            metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_CHALLENGE, reason="STABLES:resume-window-expired")
            metadata["recommended_action"] = "reauth_or_start_new_session"
            return metadata

        if not context_info.get("resume_requested"):
            metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_CHALLENGE, reason="STABLES:await-resume")
            metadata["recommended_action"] = "resume_or_expire"
            return metadata

        pending_token = str(record.get("pending_resume_token") or "")
        if not presented_token or not pending_token:
            metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_CHALLENGE, reason="STABLES:pending-resume-token-required")
            metadata["recommended_action"] = "present_pending_resume_token"
            return metadata
        if presented_token != pending_token:
            metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_QUARANTINE, reason="STABLES:pending-resume-token-mismatch")
            metadata["recommended_action"] = "quarantine_and_review"
            return metadata

        _stables_issue_token_sec(record, presented_token=presented_token, now_ts=now_ts)
        record["pending_resume_token"] = None
        record["resume_window_expires_at"] = None
        record["last_verified_at"] = _iso_now_sec()
        metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_ALLOW, reason="STABLES:resume-approved")
        metadata["rotation_window_status"] = "active"
        return metadata

    if record.get("state") == "EXPIRED":
        metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_CHALLENGE, reason="STABLES:expired")
        metadata["recommended_action"] = "start_new_session"
        return metadata

    if record.get("state") == "ABANDONED":
        metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_CHALLENGE, reason="STABLES:abandoned-human-verification-required")
        metadata["recommended_action"] = "initiate_new_session_after_human_verification"
        return metadata

    if record.get("state") == "CLOSED":
        return _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_ALLOW, reason="STABLES:closed")

    if presented_token:
        current_token = str(record.get("current_token") or "")
        if current_token and presented_token != current_token:
            metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_QUARANTINE, reason="STABLES:rotation-token-mismatch")
            metadata["recommended_action"] = "quarantine_and_review"
            return metadata
        _stables_issue_token_sec(record, presented_token=presented_token, now_ts=now_ts)
        record["last_verified_at"] = _iso_now_sec()
        return _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_ALLOW, reason="STABLES:active")

    metadata = _stables_metadata_from_record_sec(record, outcome=SECURITY_OUTCOME_ALLOW, reason="STABLES:metadata-only")
    metadata["metadata_only"] = bool(metadata_only)
    return metadata

def king_sovereignty_check(auth_token):
    """Minimal sovereign gate: returns True if auth is valid."""
    return auth_token == ROYAL_SIGNET


def scout_house_posture_sec(context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Evaluate the current environment trust posture without changing user data."""
    details = dict(context or {})
    environment = str(details.get("environment") or "local_only").strip().lower() or "local_only"
    host = str(details.get("host") or details.get("envoy_host") or "localhost").strip().lower() or "localhost"
    session_id = str(details.get("session_id") or details.get("request_id") or "").strip()
    policy = _load_trust_policy_sec()
    allowed_env = {str(v).strip().lower() for v in (policy.get("allowed_environments") or [])}
    trusted_hosts = {str(v).strip().lower() for v in (policy.get("trusted_hosts") or [])}
    trusted_host = host in trusted_hosts
    trusted_environment = environment in allowed_env
    if environment == "lan" and not bool(policy.get("allow_lan", True)):
        trusted_environment = False
    if environment == "internet_strict" and not bool(policy.get("allow_internet_strict", False)):
        trusted_environment = False
    trusted = bool(trusted_host and trusted_environment)
    posture = {
        "trusted": trusted,
        "environment": environment,
        "host": host,
        "session_id": session_id,
        "authority_layer": "SCOUT_HOUSE",
        "policy_source": "trust-policy",
        "recommended_action": SECURITY_OUTCOME_ALLOW if trusted else SECURITY_OUTCOME_CHALLENGE,
        "evaluated_at": _iso_now_sec(),
    }
    _SECURITY_KEEP_STATE["posture"] = posture
    return posture


def _validate_self_evolve_signature_sec(amip_request: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    routing_intent = str(amip_request.get("routing_intent", "")).strip().lower()
    if routing_intent != "self.evolve":
        return errors

    payload = amip_request.get("payload") if isinstance(amip_request.get("payload"), dict) else {}
    if not str(payload.get("delta_signature", "")).strip():
        errors.append("missing_self_evolve_delta_signature")
    if not str(payload.get("signed_by", "")).strip():
        errors.append("missing_self_evolve_signer")
    if bool(payload.get("dry_run", True)) is not True:
        errors.append("self_evolve_requires_dry_run")
    return errors


def _validate_contextual_routing_signals_sec(amip_request: Dict[str, Any]) -> List[str]:
    errors: List[str] = []
    payload = amip_request.get("payload") if isinstance(amip_request.get("payload"), dict) else {}
    if not isinstance(payload, dict):
        return errors

    narrative_mode = str(payload.get("narrative_mode") or payload.get("persona") or "").strip().lower()
    resonance_state = str(payload.get("resonance_state") or payload.get("resonance") or "").strip().lower()
    routing_intent = str(amip_request.get("routing_intent", "")).strip().lower()

    if routing_intent.startswith("document."):
        doc_ctx = payload.get("document_context") if isinstance(payload.get("document_context"), dict) else {}
        if doc_ctx and not str(doc_ctx.get("document_id") or "").strip():
            errors.append("document_context_missing_document_id")

    if resonance_state in {"dissonant", "unstable", "red"}:
        errors.append("resonance_state_requires_challenge")

    if narrative_mode in {"unsafe_override", "raw_bypass"}:
        errors.append("narrative_mode_denied")

    return errors


def safe_zeroize_sec(reason: str = "", scope: str = "volatile") -> Dict[str, Any]:
    """Safe zeroize clears volatile in-memory state only. It never deletes files, NBS, profiles, or envelopes."""
    volatile_cache = _SECURITY_KEEP_STATE.get("volatile_cache")
    if not isinstance(volatile_cache, dict):
        volatile_cache = {}
    cleared_keys = sorted(list(volatile_cache.keys()))
    _SECURITY_KEEP_STATE["volatile_cache"] = {}
    _SECURITY_KEEP_STATE["pending_challenges"] = []
    _SECURITY_KEEP_STATE["last_outcome"] = SECURITY_OUTCOME_ZEROIZE_SAFE
    result = {
        "ok": True,
        "action": SECURITY_OUTCOME_ZEROIZE_SAFE,
        "scope": str(scope or "volatile"),
        "cleared_keys": cleared_keys,
        "cleared_count": len(cleared_keys),
        "files_deleted": 0,
        "nbs_deleted": 0,
        "profiles_deleted": 0,
        "reason": str(reason or "volatile-state-cleared"),
        "timestamp": _iso_now_sec(),
    }
    _SECURITY_KEEP_STATE["last_zeroize"] = result
    return result


def security_vault_lifecycle_sec(action: str = "seal", reason: str = "", incident_id: str = "") -> Dict[str, Any]:
    """Safe Gen1 vault lifecycle: seal, unseal, evict (volatile only), and recover."""
    requested_action = str(action or "seal").strip().lower() or "seal"
    before_state = str(_SECURITY_KEEP_STATE.get("vault_state", "sealed"))
    zeroize_result = None

    if requested_action == "seal":
        after_state = "sealed"
    elif requested_action == "unseal":
        after_state = "unsealed"
    elif requested_action == "evict":
        after_state = "evicted"
        zeroize_result = safe_zeroize_sec(reason=reason or "vault-evict", scope="volatile")
    elif requested_action == "recover":
        after_state = "recovered"
        _SECURITY_KEEP_STATE["control_lockdown"] = False
    else:
        return {
            "ok": False,
            "reason": f"unsupported_vault_action:{requested_action}",
            "vault_state": before_state,
        }

    _SECURITY_KEEP_STATE["vault_state"] = after_state
    result = {
        "ok": True,
        "action": requested_action,
        "vault_state_before": before_state,
        "vault_state_after": after_state,
        "reason": str(reason or f"vault:{requested_action}"),
        "incident_id": str(incident_id or ""),
        "timestamp": _iso_now_sec(),
    }
    if zeroize_result is not None:
        result["zeroize"] = zeroize_result
    return result


def security_incident_lifecycle_sec(
    event_type: str = "security.incident",
    actor: str = "security",
    severity: str = "medium",
    reason: str = "",
    outcome: str = SECURITY_OUTCOME_ALLOW,
    envelope: Optional[Dict[str, Any]] = None,
    recommended_action: str = "monitor",
) -> Dict[str, Any]:
    """Record a full non-destructive incident lifecycle for audit, quarantine, lockdown, and recovery flows."""
    final_outcome = str(outcome or SECURITY_OUTCOME_ALLOW).upper()
    incident_id = f"incident-{int(datetime.now(timezone.utc).timestamp() * 1000)}"
    stages = ["DETECT", "AUDIT"]
    if final_outcome == SECURITY_OUTCOME_QUARANTINE:
        stages.append("QUARANTINE")
    elif final_outcome == SECURITY_OUTCOME_LOCKDOWN:
        stages.append("LOCKDOWN")
        _SECURITY_KEEP_STATE["control_lockdown"] = True
    elif final_outcome == SECURITY_OUTCOME_ZEROIZE_SAFE:
        stages.append("ZEROIZE_SAFE")
    else:
        stages.append("RECOVER")

    incident = {
        "incident_id": incident_id,
        "timestamp": _iso_now_sec(),
        "event_type": event_type,
        "actor": actor,
        "severity": str(severity or "medium").lower(),
        "reason": str(reason or final_outcome),
        "recommended_action": str(recommended_action or "monitor"),
        "final_disposition": final_outcome,
        "stages": stages,
        "envelope": _json_safe_sec(envelope or {}),
    }
    history = _SECURITY_KEEP_STATE.setdefault("incident_history", [])
    history.append(incident)
    if len(history) > 200:
        del history[:-200]

    sheriff_audit(event_type, actor, final_outcome, incident["reason"], details=incident)
    return incident


def evaluate_sovereignty_sec(
    auth_token: str = "",
    shunt_envelope: Optional[Dict[str, Any]] = None,
    amip_request: Optional[Dict[str, Any]] = None,
    session_id: str = "",
    environment: str = "local_only",
    host: str = "localhost",
    presented_token: str = "",
) -> Dict[str, Any]:
    """Evaluate identity, environment, session, envelope, and additive STABLES state with non-destructive outcomes."""
    envelope = dict(shunt_envelope or {})
    amip_payload = dict(amip_request or envelope.get("amip_payload") or {})
    resolved_session_id = session_id or envelope.get("request_id") or amip_payload.get("correlation_id") or ""
    posture = scout_house_posture_sec({
        "environment": environment,
        "host": host,
        "session_id": resolved_session_id,
    })
    stables = stables_validate_session_sec(
        shunt_envelope=envelope,
        amip_request=amip_payload,
        context={
            "session_id": resolved_session_id,
            "environment": environment,
            "host": host,
            "presented_token": presented_token,
        },
        metadata_only=True,
    )

    checks: Dict[str, Dict[str, Any]] = {
        "identity": {
            "ok": king_sovereignty_check(auth_token),
            "reason": "KING:sovereignty-check-passed" if king_sovereignty_check(auth_token) else "KING:sovereignty-check-failed",
        },
        "environment": {
            "ok": posture.get("trusted", False),
            "reason": "environment-trusted" if posture.get("trusted", False) else "environment-challenge-required",
        },
        "session": {
            "ok": bool(resolved_session_id),
            "reason": "session-present" if resolved_session_id else "session-missing",
        },
        "envelope": {
            "ok": True,
            "reason": "envelope-not-supplied",
        },
        "stables": {
            "ok": not stables.get("applied") or stables.get("outcome") == SECURITY_OUTCOME_ALLOW,
            "reason": stables.get("reason", "STABLES:not-applicable"),
            "hardness_state": stables.get("hardness_state", "NOT_APPLICABLE"),
            "rotation_window_status": stables.get("rotation_window_status", "not_applicable"),
        },
    }

    if envelope:
        envelope_validation = validate_bucey_shunt_sec(envelope)
        checks["envelope"] = {
            "ok": envelope_validation.get("valid", False),
            "reason": envelope_validation.get("reason", "BUCEY:unknown"),
            "errors": envelope_validation.get("errors", []),
        }
    elif amip_payload:
        amip_validation = validate_amip_payload_sec(amip_payload)
        checks["envelope"] = {
            "ok": amip_validation.get("valid", False),
            "reason": amip_validation.get("reason", "AMIP:unknown"),
            "errors": amip_validation.get("errors", []),
        }

    if not checks["identity"]["ok"]:
        outcome = SECURITY_OUTCOME_LOCKDOWN
        recommended_action = "freeze_control_and_reauth"
    elif stables.get("applied") and stables.get("outcome") == SECURITY_OUTCOME_QUARANTINE:
        outcome = SECURITY_OUTCOME_QUARANTINE
        recommended_action = "isolate_session_and_review"
    elif not checks["envelope"]["ok"]:
        outcome = SECURITY_OUTCOME_QUARANTINE
        recommended_action = "isolate_request_or_file"
    elif stables.get("applied") and stables.get("outcome") == SECURITY_OUTCOME_CHALLENGE:
        outcome = SECURITY_OUTCOME_CHALLENGE
        recommended_action = stables.get("recommended_action", "reauth_or_revalidate")
    elif not checks["environment"]["ok"] or not checks["session"]["ok"]:
        outcome = SECURITY_OUTCOME_CHALLENGE
        recommended_action = "reauth_or_revalidate"
    else:
        outcome = SECURITY_OUTCOME_ALLOW
        recommended_action = "proceed"

    _SECURITY_KEEP_STATE["last_outcome"] = outcome
    if outcome == SECURITY_OUTCOME_LOCKDOWN:
        _SECURITY_KEEP_STATE["control_lockdown"] = True
    elif outcome == SECURITY_OUTCOME_ALLOW:
        _SECURITY_KEEP_STATE["control_lockdown"] = False

    return {
        "ok": outcome == SECURITY_OUTCOME_ALLOW,
        "outcome": outcome,
        "recommended_action": recommended_action,
        "checks": checks,
        "posture": posture,
        "stables": stables,
        "vault_state": _SECURITY_KEEP_STATE.get("vault_state", "sealed"),
        "timestamp": _iso_now_sec(),
    }

# ===========================================================================
# PALADIN GATE (allow / deny decision)
# ===========================================================================
BAD_SIGNATURES = ["drop table", "sudo", "delete", "rm -rf", "force", "hack"]

def paladin_gate(request_text):
    """Returns (allowed: bool, reason: str)."""
    content = str(request_text).lower()
    for sig in BAD_SIGNATURES:
        if sig in content:
            return False, f"PALADIN:DENY:hostile-signature:{sig}"
    return True, "PALADIN:ALLOW:clean"

# ===========================================================================
# SHERIFF AUDIT (structured event record)
# ===========================================================================
def sheriff_audit(event_type, actor, decision, reason, details: Optional[Dict[str, Any]] = None, **extra):
    """Writes a single audit line; returns the event dict with optional structured metadata."""
    event = {
        "ts": _iso_now_sec(),
        "event_type": event_type,
        "actor": actor,
        "decision": decision,
        "reason": reason,
    }
    if isinstance(details, dict) and details:
        event["details"] = _json_safe_sec(details)
    if extra:
        event.update(_json_safe_sec(extra))
    audit_dir = os.path.join(os.path.dirname(__file__), "logs")
    os.makedirs(audit_dir, exist_ok=True)
    audit_path = os.path.join(audit_dir, "security_audit.ndjson")
    with open(audit_path, "a", encoding="utf-8") as f:
        f.write(json.dumps(event, ensure_ascii=False) + "\n")
    return event

# ===========================================================================
# HARNESS PROOF RUN
# ===========================================================================
def run_security_harness_check(auth_token=ROYAL_SIGNET, request_text="harness:proof:run"):
    """
    Runs the security pillar gate sequence for a harness proof test.
    Returns a result dict with keys: status, reason.
    """
    # Step 1 -- sovereignty check
    if not king_sovereignty_check(auth_token):
        sheriff_audit("security.harness.proof", "king", "DENY", "KING:sovereignty-check-failed")
        return {"status": "FAIL", "reason": "KING:sovereignty-check-failed"}

    # Step 2 -- paladin gate
    allowed, reason = paladin_gate(request_text)
    if not allowed:
        sheriff_audit("security.harness.proof", "paladin", "DENY", reason)
        return {"status": "FAIL", "reason": reason}

    # Step 3 -- sheriff audit record for the passing path
    event = sheriff_audit("security.harness.proof", "sheriff", "ALLOW", reason)

    return {"status": "PASS", "reason": reason, "audit": event}


if __name__ == "__main__":
    print("=" * 55)
    print("SARA SECURITY: Gen0 Harness Proof Test")
    print("=" * 55)
    result = run_security_harness_check()
    print(f"  Status : {result['status']}")
    print(f"  Reason : {result['reason']}")
    print("=" * 55)

# =============================================================================
# SECURITY FSM ROUTER  (shunt_header: sara_security_gen1_base)
# evolution anchor: this file is the baseline for all Sara_security shunt expansions
# =============================================================================
# All security operations route through dispatch_security().
# Control is the only caller that should reach this layer.
#
# Flow (internal to security pillar):
#   control → dispatch_security(command, auth_token, **kwargs)
#                └→ king_sovereignty_check
#                    └→ paladin_gate
#                        └→ sheriff_audit
#                            └→ SecurityFSM.handle(command)
#                                └→ registered action
#                                    └→ result back to control
# =============================================================================

import importlib.util as _ilu
import os as _os
import threading as _threading

# --- Load ShuntFSM from Gen1 core ---
def _load_shunt_fsm():
    _here = _os.path.dirname(_os.path.abspath(__file__))
    _candidates = [
        ("sara_coregen1_sec", _os.path.join(_here, "..", "sara_core", "sara_coregen1.py")),
        ("sara_coregn1_sec", _os.path.join(_here, "..", "sara_core", "sara_coregn1.py")),
    ]
    for _module_name, _path in _candidates:
        if not _os.path.exists(_path):
            continue
        _spec = _ilu.spec_from_file_location(_module_name, _path)
        if _spec is None or _spec.loader is None:
            continue
        _mod = _ilu.module_from_spec(_spec)
        _spec.loader.exec_module(_mod)
        return _mod.ShuntFSM
    raise FileNotFoundError("Could not locate Gen1 CORE FSM module. Checked sara_coregen1.py and sara_coregn1.py")

ShuntFSM = _load_shunt_fsm()


# --- Command wrappers ---

def _cmd_gate_check(kwargs):
    """Run the full king→paladin→sheriff sequence on an arbitrary request."""
    token = kwargs.get("auth_token", "")
    text = str(kwargs.get("text", ""))
    if not king_sovereignty_check(token):
        event = sheriff_audit("gate_check", "king", "DENY", "KING:sovereignty-check-failed")
        return {"allowed": False, "reason": "KING:sovereignty-check-failed", "audit": event}
    allowed, reason = paladin_gate(text)
    decision = "ALLOW" if allowed else "DENY"
    event = sheriff_audit("gate_check", "sheriff" if allowed else "paladin", decision, reason)
    return {"allowed": allowed, "reason": reason, "audit": event}


def _cmd_trust_posture(kwargs):
    context = kwargs.get("context") or {}
    if not isinstance(context, dict):
        context = {"environment": kwargs.get("environment", "local_only"), "host": kwargs.get("host", "localhost")}
    context.setdefault("environment", kwargs.get("environment", context.get("environment", "local_only")))
    context.setdefault("host", kwargs.get("host", context.get("host", "localhost")))
    context.setdefault("session_id", kwargs.get("session_id", context.get("session_id", "")))
    return scout_house_posture_sec(context)


def _cmd_evaluate_sovereignty(kwargs):
    result = evaluate_sovereignty_sec(
        auth_token=kwargs.get("auth_token", ""),
        shunt_envelope=kwargs.get("shunt_envelope") or kwargs.get("envelope") or {},
        amip_request=kwargs.get("amip_request") or kwargs.get("payload") or {},
        session_id=str(kwargs.get("session_id", "") or ""),
        environment=str(kwargs.get("environment", "local_only") or "local_only"),
        host=str(kwargs.get("host", "localhost") or "localhost"),
    )
    if result.get("outcome") != SECURITY_OUTCOME_ALLOW:
        incident = security_incident_lifecycle_sec(
            event_type="security.sovereignty",
            actor="king",
            severity="high" if result.get("outcome") == SECURITY_OUTCOME_LOCKDOWN else "medium",
            reason=result.get("recommended_action", "review"),
            outcome=result.get("outcome", SECURITY_OUTCOME_CHALLENGE),
            envelope=kwargs.get("shunt_envelope") or kwargs.get("envelope") or kwargs.get("amip_request") or {},
            recommended_action=result.get("recommended_action", "review"),
        )
        result["incident"] = incident
    return result


def _cmd_vault_lifecycle(kwargs):
    return security_vault_lifecycle_sec(
        action=str(kwargs.get("action", "seal") or "seal"),
        reason=str(kwargs.get("reason", "") or ""),
        incident_id=str(kwargs.get("incident_id", "") or ""),
    )


def _cmd_safe_zeroize(kwargs):
    return safe_zeroize_sec(
        reason=str(kwargs.get("reason", "manual-safe-zeroize") or "manual-safe-zeroize"),
        scope=str(kwargs.get("scope", "volatile") or "volatile"),
    )


def _cmd_incident_lifecycle(kwargs):
    return security_incident_lifecycle_sec(
        event_type=str(kwargs.get("event_type", "security.incident") or "security.incident"),
        actor=str(kwargs.get("actor", "security") or "security"),
        severity=str(kwargs.get("severity", "medium") or "medium"),
        reason=str(kwargs.get("reason", "") or ""),
        outcome=str(kwargs.get("outcome", SECURITY_OUTCOME_ALLOW) or SECURITY_OUTCOME_ALLOW),
        envelope=kwargs.get("envelope") or kwargs.get("shunt_envelope") or {},
        recommended_action=str(kwargs.get("recommended_action", "monitor") or "monitor"),
    )

def _cmd_audit_write(kwargs):
    """Write an explicit audit record (for events originating outside normal gate flow)."""
    return sheriff_audit(
        kwargs.get("event_type", "manual"),
        kwargs.get("actor", "system"),
        kwargs.get("decision", "ALLOW"),
        kwargs.get("reason", ""),
    )

def _cmd_paladin_scan(kwargs):
    """Pure signature scan — no sovereignty check, no audit write."""
    allowed, reason = paladin_gate(str(kwargs.get("text", "")))
    return {"allowed": allowed, "reason": reason}


_AMI_ID_RE = re.compile(r"^[0-9A-Fa-f]{4}\s[0-9A-Fa-f]{8}\s[0-9A-Fa-f]{4}$")
_AMIP_REQUIRED_FIELDS = {
    "amip_version",
    "mode",
    "routing_intent",
    "resource_budget",
    "payload",
    "machine_profile",
    "correlation_id",
}


def validate_ami_id_sec(ami_id: str) -> Dict[str, Any]:
    value = str(ami_id or "").strip()
    valid = bool(_AMI_ID_RE.match(value))
    return {
        "valid": valid,
        "ami_id": value,
        "reason": "AMI:valid" if valid else "AMI:invalid-format",
    }


def validate_amip_payload_sec(amip_request: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(amip_request, dict):
        return {"valid": False, "reason": "AMIP:payload-not-dict", "errors": ["payload must be a dict"]}

    errors: List[str] = []
    missing = sorted(field for field in _AMIP_REQUIRED_FIELDS if field not in amip_request)
    if missing:
        errors.append(f"missing_fields:{','.join(missing)}")

    if str(amip_request.get("amip_version", "")) != "0.1":
        errors.append("invalid_amip_version")

    mode = str(amip_request.get("mode", "")).strip().lower()
    if mode not in {"interactive", "night_shift"}:
        errors.append("invalid_mode")

    routing_intent = str(amip_request.get("routing_intent", "")).strip()
    if not routing_intent:
        errors.append("missing_routing_intent")

    budget = amip_request.get("resource_budget")
    if not isinstance(budget, dict):
        errors.append("resource_budget_not_dict")
    else:
        if str(budget.get("strain", "")).strip().lower() not in {"low", "medium", "high"}:
            errors.append("invalid_strain")
        if not isinstance(budget.get("tokens", None), int):
            errors.append("tokens_not_int")
        if not isinstance(budget.get("runtime_ms", None), int):
            errors.append("runtime_ms_not_int")

    machine_profile = amip_request.get("machine_profile")
    if not isinstance(machine_profile, dict) or not str(machine_profile.get("profile_id", "")).strip():
        errors.append("invalid_machine_profile")

    correlation_id = str(amip_request.get("correlation_id", "")).strip()
    if not correlation_id:
        errors.append("missing_correlation_id")

    errors.extend(_validate_self_evolve_signature_sec(amip_request))
    errors.extend(_validate_contextual_routing_signals_sec(amip_request))

    return {
        "valid": len(errors) == 0,
        "reason": "AMIP:valid" if not errors else "AMIP:invalid",
        "errors": errors,
        "routing_intent": routing_intent,
        "mode": mode or "interactive",
        "correlation_id": correlation_id,
    }


def validate_bucey_shunt_sec(shunt_envelope: Dict[str, Any]) -> Dict[str, Any]:
    if not isinstance(shunt_envelope, dict):
        return {"valid": False, "reason": "BUCEY:envelope-not-dict", "errors": ["envelope must be a dict"]}

    errors: List[str] = []
    header = shunt_envelope.get("header")
    if not isinstance(header, dict):
        errors.append("missing_header")

    ami_validation = validate_ami_id_sec(shunt_envelope.get("ami_id", ""))
    if not ami_validation.get("valid"):
        errors.append("invalid_ami_id")

    if "amip_payload" not in shunt_envelope or not isinstance(shunt_envelope.get("amip_payload"), dict):
        errors.append("missing_amip_payload")

    if not str(shunt_envelope.get("correlation_id", "")).strip():
        errors.append("missing_correlation_id")

    if not str(shunt_envelope.get("request_id", "")).strip():
        errors.append("missing_request_id")

    stables = stables_validate_session_sec(
        shunt_envelope=shunt_envelope,
        amip_request=shunt_envelope.get("amip_payload") if isinstance(shunt_envelope.get("amip_payload"), dict) else {},
        metadata_only=True,
    )

    return {
        "valid": len(errors) == 0,
        "reason": "BUCEY:valid" if not errors else "BUCEY:invalid",
        "errors": errors,
        "ami_validation": ami_validation,
        "stables": stables,
    }


def audit_amip_event_sec(event_type: str, amip_request: Optional[Dict[str, Any]] = None, decision: str = "ALLOW", reason: str = "AMIP:event") -> Dict[str, Any]:
    request = dict(amip_request or {})
    route = str(request.get("routing_intent", "unknown"))
    correlation_id = str(request.get("correlation_id", "unknown"))
    audit_reason = f"{reason}|route={route}|correlation_id={correlation_id}"
    return sheriff_audit(event_type, "amip", decision, audit_reason)


def _cmd_validate_amip(kwargs):
    amip_request = kwargs.get("amip_request") or kwargs.get("payload") or {}
    validation = validate_amip_payload_sec(amip_request)
    audit = audit_amip_event_sec(
        "security.validate_amip",
        amip_request=amip_request,
        decision="ALLOW" if validation.get("valid") else "DENY",
        reason=validation.get("reason", "AMIP:unknown"),
    )
    validation["audit"] = audit
    return validation


def _cmd_validate_bucey_shunt(kwargs):
    shunt_envelope = kwargs.get("shunt_envelope") or kwargs.get("envelope") or {}
    validation = validate_bucey_shunt_sec(shunt_envelope)
    validation["stables"] = stables_validate_session_sec(
        shunt_envelope=shunt_envelope,
        amip_request=shunt_envelope.get("amip_payload") if isinstance(shunt_envelope, dict) else {},
        context={
            "presented_token": kwargs.get("presented_token") or kwargs.get("stables_token") or "",
            "resume_requested": bool(kwargs.get("resume_requested", False)),
        },
        metadata_only=True,
    )

    amip_request = shunt_envelope.get("amip_payload") if isinstance(shunt_envelope, dict) else {}
    audit = audit_amip_event_sec(
        "security.validate_bucey_shunt",
        amip_request=amip_request if isinstance(amip_request, dict) else {},
        decision="ALLOW" if validation.get("valid") else "DENY",
        reason=validation.get("reason", "BUCEY:unknown"),
    )
    validation["audit"] = audit
    return validation


def validate_mail_transport_sec(amip_request: Dict[str, Any]) -> Dict[str, Any]:
    request = dict(amip_request or {})
    routing_intent = str(request.get("routing_intent") or "").strip().lower()
    payload = request.get("payload") if isinstance(request.get("payload"), dict) else {}
    core_config = payload.get("core_config") if isinstance(payload.get("core_config"), dict) else {}

    allowed_intents = {"mail.smtp.send", "mail.imap.fetch"}
    if routing_intent not in allowed_intents:
        return {
            "valid": False,
            "reason": "MAIL:unsupported-routing-intent",
            "routing_intent": routing_intent,
        }

    if routing_intent == "mail.smtp.send":
        email_data = payload.get("email_data") if isinstance(payload.get("email_data"), dict) else {}
        missing_fields = [f for f in ["to", "from", "subject", "body"] if not str(email_data.get(f, "")).strip()]
        smtp_host = str(core_config.get("smtp_host", "")).strip()
        if missing_fields:
            return {
                "valid": False,
                "reason": "MAIL:smtp-missing-email-fields",
                "missing_fields": missing_fields,
                "routing_intent": routing_intent,
            }
        if not smtp_host:
            return {
                "valid": False,
                "reason": "MAIL:smtp-host-required",
                "routing_intent": routing_intent,
            }
        probe_text = f"{email_data.get('subject', '')} {email_data.get('body', '')}"
    else:
        imap_host = str(core_config.get("imap_host", "")).strip()
        username = str(core_config.get("username", "")).strip()
        if not imap_host or not username:
            return {
                "valid": False,
                "reason": "MAIL:imap-host-username-required",
                "routing_intent": routing_intent,
            }
        probe_text = str(core_config.get("criteria", "ALL"))

    allowed, gate_reason = paladin_gate(probe_text)
    if not allowed:
        return {
            "valid": False,
            "reason": gate_reason,
            "routing_intent": routing_intent,
        }

    return {
        "valid": True,
        "reason": "MAIL:allow",
        "routing_intent": routing_intent,
    }


def _cmd_validate_mail_transport(kwargs):
    amip_request = kwargs.get("amip_request") or kwargs.get("payload") or {}
    validation = validate_mail_transport_sec(amip_request)
    audit = audit_amip_event_sec(
        "security.validate_mail_transport",
        amip_request=amip_request if isinstance(amip_request, dict) else {},
        decision="ALLOW" if validation.get("valid") else "DENY",
        reason=validation.get("reason", "MAIL:unknown"),
    )
    validation["audit"] = audit
    return validation


def _cmd_stables_init_session(kwargs):
    result = stables_init_session_sec(
        shunt_envelope=kwargs.get("shunt_envelope") or kwargs.get("envelope") or {},
        amip_request=kwargs.get("amip_request") or kwargs.get("payload") or {},
        context=kwargs.get("context") or kwargs,
    )
    result["audit"] = sheriff_audit("security.stables.init", "sheriff", result.get("outcome", SECURITY_OUTCOME_ALLOW), result.get("reason", "STABLES:init"), details=result)
    return result


def _cmd_stables_validate_session(kwargs):
    result = stables_validate_session_sec(
        shunt_envelope=kwargs.get("shunt_envelope") or kwargs.get("envelope") or {},
        amip_request=kwargs.get("amip_request") or kwargs.get("payload") or {},
        context=kwargs.get("context") or kwargs,
        metadata_only=bool(kwargs.get("metadata_only", False)),
    )
    if result.get("applied"):
        result["audit"] = sheriff_audit("security.stables.validate", "sheriff", result.get("outcome", SECURITY_OUTCOME_ALLOW), result.get("reason", "STABLES:validate"), details=result)
    return result


def _cmd_stables_mark_session_drop(kwargs):
    result = stables_mark_session_drop_sec(
        shunt_envelope=kwargs.get("shunt_envelope") or kwargs.get("envelope") or {},
        amip_request=kwargs.get("amip_request") or kwargs.get("payload") or {},
        context=kwargs.get("context") or kwargs,
    )
    if result.get("applied"):
        result["audit"] = sheriff_audit("security.stables.drop", "sheriff", result.get("outcome", SECURITY_OUTCOME_CHALLENGE), result.get("reason", "STABLES:await-resume"), details=result)
    return result


def _cmd_stables_resume_session(kwargs):
    context = dict(kwargs.get("context") or kwargs)
    context["resume_requested"] = True
    result = stables_validate_session_sec(
        shunt_envelope=kwargs.get("shunt_envelope") or kwargs.get("envelope") or {},
        amip_request=kwargs.get("amip_request") or kwargs.get("payload") or {},
        context=context,
    )
    if result.get("applied"):
        result["audit"] = sheriff_audit("security.stables.resume", "sheriff", result.get("outcome", SECURITY_OUTCOME_CHALLENGE), result.get("reason", "STABLES:resume"), details=result)
    return result


def _cmd_stables_close_session(kwargs):
    result = stables_close_session_sec(
        shunt_envelope=kwargs.get("shunt_envelope") or kwargs.get("envelope") or {},
        amip_request=kwargs.get("amip_request") or kwargs.get("payload") or {},
        context=kwargs.get("context") or kwargs,
    )
    if result.get("applied"):
        result["audit"] = sheriff_audit("security.stables.close", "sheriff", result.get("outcome", SECURITY_OUTCOME_ALLOW), result.get("reason", "STABLES:closed"), details=result)
    return result


def _sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _find_windows_defender_cli():
    candidates = []
    env_pf = os.environ.get("ProgramFiles", r"C:\Program Files")
    candidates.append(os.path.join(env_pf, "Windows Defender", "MpCmdRun.exe"))
    candidates.extend(glob.glob(r"C:\ProgramData\Microsoft\Windows Defender\Platform\*\MpCmdRun.exe"))
    for p in candidates:
        if os.path.exists(p):
            return p
    return None


def _scan_with_windows_defender(file_path, timeout_sec=45):
    mpcmd = _find_windows_defender_cli()
    if not mpcmd:
        return {"available": False, "status": "not_available", "detail": "MpCmdRun.exe not found"}
    try:
        proc = subprocess.run(
            [mpcmd, "-Scan", "-ScanType", "3", "-File", file_path],
            capture_output=True,
            text=True,
            timeout=max(5, int(timeout_sec)),
            check=False,
        )
        # Defender return codes vary by version, so we inspect output text too.
        out = f"{proc.stdout}\n{proc.stderr}".lower()
        if "found" in out and "threat" in out:
            return {
                "available": True,
                "status": "threat_found",
                "exit_code": proc.returncode,
                "detail": out[-4000:],
            }
        if proc.returncode == 0:
            return {
                "available": True,
                "status": "clean",
                "exit_code": proc.returncode,
                "detail": out[-2000:],
            }
        return {
            "available": True,
            "status": "scan_error",
            "exit_code": proc.returncode,
            "detail": out[-4000:],
        }
    except Exception as e:
        return {"available": True, "status": "scan_exception", "detail": str(e)}


def _quarantine_file(file_path, reason):
    q_dir = os.path.join(os.path.dirname(__file__), "quarantine")
    os.makedirs(q_dir, exist_ok=True)
    base = os.path.basename(file_path)
    stamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    q_path = os.path.join(q_dir, f"q_{stamp}_{base}")
    try:
        shutil.move(file_path, q_path)
        return {"moved": True, "quarantine_path": q_path, "reason": reason}
    except Exception as e:
        return {"moved": False, "quarantine_path": None, "reason": f"{reason};quarantine-move-failed:{e}"}


def _scan_file_policy(file_path, file_ext="", is_envoy=False, max_file_bytes=100 * 1024 * 1024):
    if not file_path or not os.path.exists(file_path):
        return {"allowed": False, "reason": "SEC:DENY:file-missing"}

    try:
        size = os.path.getsize(file_path)
    except Exception:
        return {"allowed": False, "reason": "SEC:DENY:size-read-failed"}

    if size <= 0:
        return {"allowed": False, "reason": "SEC:DENY:file-empty", "size": size}
    if size > int(max_file_bytes):
        return {"allowed": False, "reason": "SEC:DENY:file-too-large", "size": size}

    ext = (file_ext or os.path.splitext(file_path)[1] or "").lower()
    denied_exec_exts = {".exe", ".dll", ".bat", ".cmd", ".ps1", ".js", ".vbs", ".scr", ".com", ".msi"}
    if ext in denied_exec_exts:
        return {"allowed": False, "reason": f"SEC:DENY:blocked-ext:{ext}", "size": size}

    if is_envoy:
        # Envoy is an incoming I/O protocol: keep format strict and explicit.
        envoy_allowed = {
            ".json", ".nbs", ".txt", ".md", ".csv", ".pdf", ".docx", ".xlsx", ".xls",
            ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".tiff", ".webp", ".zip",
            ".mp4", ".mov", ".avi", ".mkv", ".webm",
            ".mp3", ".wav", ".flac", ".ogg", ".m4a", ".aac",
            ".stl", ".obj",
        }
        if ext and ext not in envoy_allowed:
            return {"allowed": False, "reason": f"SEC:DENY:envoy-ext-not-allowed:{ext}", "size": size}

    try:
        with open(file_path, "rb") as f:
            head = f.read(8192)
    except Exception:
        return {"allowed": False, "reason": "SEC:DENY:read-head-failed", "size": size}

    low_head = head.lower()
    bad_markers = [
        b"powershell -", b"cmd.exe", b"<script", b"wscript", b"cscript", b"mshta",
        b"mimikatz", b"invoke-expression", b"downloadstring",
    ]
    for marker in bad_markers:
        if marker in low_head:
            return {"allowed": False, "reason": f"SEC:DENY:signature:{marker.decode('utf-8', errors='ignore')}", "size": size}

    digest = None
    try:
        digest = _sha256_file(file_path)
    except Exception:
        digest = None

    return {
        "allowed": True,
        "reason": "SEC:ALLOW:policy-clean",
        "size": size,
        "sha256": digest,
        "ext": ext,
    }


def _cmd_scan_file(kwargs):
    """Scan a staged file with policy checks and optional Defender scan."""
    file_path = kwargs.get("file_path", "")
    file_ext = kwargs.get("file_ext", "")
    max_file_bytes = kwargs.get("max_file_bytes", 100 * 1024 * 1024)
    run_defender = bool(kwargs.get("use_windows_defender", True))

    policy = _scan_file_policy(
        file_path=file_path,
        file_ext=file_ext,
        is_envoy=False,
        max_file_bytes=max_file_bytes,
    )
    if not policy.get("allowed"):
        q = _quarantine_file(file_path, policy.get("reason", "SEC:DENY:policy"))
        sheriff_audit("security.scan_file", "sheriff", "DENY", q.get("reason", policy.get("reason", "deny")))
        return {
            "allowed": False,
            "reason": q.get("reason", policy.get("reason", "deny")),
            "quarantine": q,
            "policy": policy,
        }

    defender = {"available": False, "status": "disabled", "detail": "disabled by request"}
    if run_defender:
        defender = _scan_with_windows_defender(file_path)
        if defender.get("available") and defender.get("status") == "threat_found":
            q = _quarantine_file(file_path, "SEC:DENY:defender-threat")
            sheriff_audit("security.scan_file", "sheriff", "DENY", "SEC:DENY:defender-threat")
            return {
                "allowed": False,
                "reason": "SEC:DENY:defender-threat",
                "quarantine": q,
                "policy": policy,
                "defender": defender,
            }

    sheriff_audit("security.scan_file", "sheriff", "ALLOW", "SEC:ALLOW:file-clean")
    return {"allowed": True, "reason": "SEC:ALLOW:file-clean", "policy": policy, "defender": defender}


def _validate_vnce_envoy_record(envoy_record: dict) -> dict:
    """
    SECURITY-only VNCE envoy validator. Ensures correct schema, token, caps, and policy.
    """
    if not isinstance(envoy_record, dict):
        raise ValueError("VNCE envoy record must be a dict")

    if envoy_record.get("type") != "envoy":
        raise ValueError("VNCE envoy record must have type='envoy'")

    if envoy_record.get("protocol") != ENVOY_PROTOCOL_VNCE:
        raise ValueError("VNCE envoy record must have protocol='vnce'")

    host = envoy_record.get("host")
    port = envoy_record.get("port")
    token = envoy_record.get("token")

    if not host or not isinstance(host, str):
        raise ValueError("VNCE envoy host is required")

    if not isinstance(port, int) or port <= 0:
        raise ValueError("VNCE envoy port must be a positive integer")

    if not token or not isinstance(token, str):
        raise ValueError("VNCE envoy token is required")

    caps = envoy_record.get("caps") or []
    if "frame" not in caps or "input" not in caps:
        raise ValueError("VNCE envoy caps must include 'frame' and 'input'")

    policy = envoy_record.get("policy")
    if policy is not None and not isinstance(policy, list):
        raise ValueError("VNCE envoy policy must be a list if provided")

    return envoy_record


def _cmd_scan_envoy(kwargs):
    """Envoy intake scan: strict extension policy + optional Defender scan."""
    file_path = kwargs.get("file_path", "")
    file_ext = kwargs.get("file_ext", "")
    max_file_bytes = kwargs.get("max_file_bytes", 100 * 1024 * 1024)
    run_defender = bool(kwargs.get("use_windows_defender", True))

    policy = _scan_file_policy(
        file_path=file_path,
        file_ext=file_ext,
        is_envoy=True,
        max_file_bytes=max_file_bytes,
    )
    if not policy.get("allowed"):
        q = _quarantine_file(file_path, policy.get("reason", "SEC:DENY:envoy-policy"))
        sheriff_audit("security.scan_envoy", "sheriff", "DENY", q.get("reason", policy.get("reason", "deny")))
        return {
            "allowed": False,
            "reason": q.get("reason", policy.get("reason", "deny")),
            "quarantine": q,
            "policy": policy,
        }

    defender = {"available": False, "status": "disabled", "detail": "disabled by request"}
    if run_defender:
        defender = _scan_with_windows_defender(file_path)
        if defender.get("available") and defender.get("status") == "threat_found":
            q = _quarantine_file(file_path, "SEC:DENY:envoy-defender-threat")
            sheriff_audit("security.scan_envoy", "sheriff", "DENY", "SEC:DENY:envoy-defender-threat")
            return {
                "allowed": False,
                "reason": "SEC:DENY:envoy-defender-threat",
                "quarantine": q,
                "policy": policy,
                "defender": defender,
            }

    sheriff_audit("security.scan_envoy", "sheriff", "ALLOW", "SEC:ALLOW:envoy-clean")
    return {"allowed": True, "reason": "SEC:ALLOW:envoy-clean", "policy": policy, "defender": defender}


def _cmd_attest_vnce_session(kwargs: dict) -> dict:
    """
    SECURITY-only attestation for VNCE Envoy sessions.
    Performs sovereignty check, VNCE validation, and audit.
    """
    auth_token = kwargs.get("auth_token", "")
    envoy_record = kwargs.get("envoy_record") or {}

    sovereignty = evaluate_sovereignty_sec(
        auth_token=auth_token,
        session_id=str(envoy_record.get("session_id", "") or ""),
        environment=str(envoy_record.get("environment", "local_only") or "local_only"),
        host=str(envoy_record.get("host", "localhost") or "localhost"),
    )
    if sovereignty.get("outcome") == SECURITY_OUTCOME_LOCKDOWN:
        sheriff_audit("vnce_attest_denied", "king", "LOCKDOWN", "invalid_auth_token", details=sovereignty)
        return {"ok": False, "reason": "invalid_auth_token", "sovereignty": sovereignty}

    try:
        _validate_vnce_envoy_record(envoy_record)
    except Exception as exc:
        sheriff_audit("vnce_attest_denied", "sheriff", "DENY", str(exc), details={"envoy_record": envoy_record})
        return {"ok": False, "reason": str(exc), "sovereignty": sovereignty}

    session_id = str(envoy_record.get("session_id") or "")
    host = str(envoy_record.get("host") or "")
    is_resume_or_reconnect = bool(envoy_record.get("resume_requested") or envoy_record.get("reconnect_requested"))
    if is_resume_or_reconnect:
        last = _SECURITY_KEEP_STATE.setdefault("vnce_last_attested", {}).get(session_id)
        if isinstance(last, dict):
            last_host = str(last.get("host") or "")
            if last_host and host and host != last_host:
                sheriff_audit(
                    "vnce_attest_denied",
                    "sheriff",
                    "QUARANTINE",
                    "vnce_resume_reconnect_host_mismatch",
                    details={"session_id": session_id, "previous_host": last_host, "presented_host": host},
                )
                return {"ok": False, "reason": "vnce_resume_reconnect_host_mismatch", "sovereignty": sovereignty}

    if session_id:
        _SECURITY_KEEP_STATE.setdefault("vnce_last_attested", {})[session_id] = {
            "host": host,
            "attested_at": _iso_now_sec(),
        }

    sheriff_audit(
        "vnce_attest_approved",
        "sheriff",
        "ALLOW",
        "vnce-session-approved",
        details={"host": envoy_record.get("host"), "port": envoy_record.get("port")},
    )
    return {"ok": True, "reason": "approved", "sovereignty": sovereignty}

def _cmd_harness_proof(kwargs):
    """Run the full harness proof sequence."""
    return run_security_harness_check(
        auth_token=kwargs.get("auth_token", ROYAL_SIGNET),
        request_text=kwargs.get("request_text", "harness:proof:run"),
    )


# --- FSM instance for security pillar ---
_SECURITY_FSM_LOCK = _threading.Lock()

_SECURITY_FSM = ShuntFSM(
    states=["ready", "blocked"],
    transitions={
        ("ready",   "gate_check"):    ("ready",   _cmd_gate_check),
        ("ready",   "audit_write"):   ("ready",   _cmd_audit_write),
        ("ready",   "paladin_scan"):  ("ready",   _cmd_paladin_scan),
        ("ready",   SECURITY_CMD_TRUST_POSTURE): ("ready", _cmd_trust_posture),
        ("ready",   SECURITY_CMD_EVALUATE_SOVEREIGNTY): ("ready", _cmd_evaluate_sovereignty),
        ("ready",   SECURITY_CMD_VAULT_LIFECYCLE): ("ready", _cmd_vault_lifecycle),
        ("ready",   SECURITY_CMD_INCIDENT_LIFECYCLE): ("ready", _cmd_incident_lifecycle),
        ("ready",   SECURITY_CMD_SAFE_ZEROIZE): ("ready", _cmd_safe_zeroize),
        ("ready",   STABLES_CMD_INIT_SESSION): ("ready", _cmd_stables_init_session),
        ("ready",   STABLES_CMD_VALIDATE_SESSION): ("ready", _cmd_stables_validate_session),
        ("ready",   STABLES_CMD_MARK_SESSION_DROP): ("ready", _cmd_stables_mark_session_drop),
        ("ready",   STABLES_CMD_RESUME_SESSION): ("ready", _cmd_stables_resume_session),
        ("ready",   STABLES_CMD_CLOSE_SESSION): ("ready", _cmd_stables_close_session),
        ("ready",   "scan_file"):     ("ready",   _cmd_scan_file),
        ("ready",   "scan_envoy"):    ("ready",   _cmd_scan_envoy),
        ("ready",   "validate_amip"): ("ready",   _cmd_validate_amip),
        ("ready",   "validate_bucey_shunt"): ("ready", _cmd_validate_bucey_shunt),
        ("ready",   "validate_mail_transport"): ("ready", _cmd_validate_mail_transport),
        ("ready",   SECURITY_CMD_ATTEST_VNCE_SESSION): ("ready", _cmd_attest_vnce_session),
        ("ready",   "harness_proof"): ("ready",   _cmd_harness_proof),
        ("blocked", "reset"):         ("ready",   None),
    },
    initial_state="ready",
)


def dispatch_security(command: str, auth_token: str = "", **kwargs) -> dict:
    """
    Single entry point for all security pillar operations.
    Intended to be called only by Control (not by external callers directly).

    Args:
        command:    control-routed security command name
        auth_token: must equal ROYAL_SIGNET to pass king check
        **kwargs:   command-specific arguments

    Returns:
        dict with at minimum {"success": bool}.
    """
    with _SECURITY_FSM_LOCK:
        lockdown_exempt = {
            "audit_write",
            SECURITY_CMD_TRUST_POSTURE,
            SECURITY_CMD_EVALUATE_SOVEREIGNTY,
            SECURITY_CMD_VAULT_LIFECYCLE,
            SECURITY_CMD_INCIDENT_LIFECYCLE,
            SECURITY_CMD_SAFE_ZEROIZE,
            "harness_proof",
        }
        if _SECURITY_KEEP_STATE.get("control_lockdown") and command not in lockdown_exempt:
            audit_event = sheriff_audit("dispatch_security", "king", "LOCKDOWN", "KING:control-lockdown-active")
            return {
                "success": False,
                "status": SECURITY_OUTCOME_LOCKDOWN,
                "reason": "KING:control-lockdown-active",
                "security_audit": audit_event,
            }

        # Step 1 — sovereignty check
        if not king_sovereignty_check(auth_token):
            _SECURITY_KEEP_STATE["control_lockdown"] = True
            sheriff_audit("dispatch_security", "king", "DENY", "KING:sovereignty-check-failed")
            if _SECURITY_FSM.state == "ready":
                _SECURITY_FSM.state = "blocked"
            return {"success": False, "status": "DENY", "reason": "KING:sovereignty-check-failed"}

        # Step 2 — paladin gate (scan the command + relevant text payload)
        gate_text = " ".join([
            str(command),
            str(kwargs.get("text", "")),
            str(kwargs.get("request_text", "")),
            str(kwargs.get("reason", "")),
            str(kwargs.get("routing_intent", "")),
        ])
        allowed, reason = paladin_gate(gate_text)
        if not allowed:
            sheriff_audit("dispatch_security", "paladin", "DENY", reason)
            if _SECURITY_FSM.state == "ready":
                _SECURITY_FSM.state = "blocked"
            return {"success": False, "status": "DENY", "reason": reason}

        # Step 3 — audit clean path
        audit_event = sheriff_audit("dispatch_security", "sheriff", "ALLOW", reason)

        # Recover from blocked if needed
        if _SECURITY_FSM.state == "blocked":
            _SECURITY_FSM.handle("reset")

        # Step 4 — FSM dispatch
        fsm_kwargs = dict(kwargs)
        fsm_kwargs["auth_token"] = auth_token
        fsm_kwargs["_dispatch_auth_token"] = auth_token
        fsm_result = _SECURITY_FSM.handle(command, fsm_kwargs)
        if not fsm_result.get("success"):
            return {
                "success": False,
                "error": fsm_result.get("error", "unknown FSM error"),
                "security_audit": audit_event,
            }

        result = fsm_result.get("result")
        if isinstance(result, dict) and result.get("outcome") == SECURITY_OUTCOME_LOCKDOWN:
            _SECURITY_KEEP_STATE["control_lockdown"] = True

        return {
            "success": True,
            "command": command,
            "result": result,
            "fsm_state": _SECURITY_FSM.get_state(),
            "security_audit": audit_event,
        }


def scan_image_con(
    con_image_path: str,
    con_project: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Scan an image file for metadata, size, format anomalies.
    Check for embedded scripts or suspicious EXIF data.

    Args:
        con_image_path : path to image file to scan
        con_project    : optional, writes NBS audit wrapper

    Returns dict with 'success', 'threats' list, 'metadata'.
    Requires: Pillow
    """
    try:
        pil_image = importlib.import_module("PIL.Image")
    except Exception:
        return {"success": False, "error": "Pillow not installed (pip install Pillow)"}

    if not os.path.exists(con_image_path):
        return {"success": False, "error": f"File not found: {con_image_path}"}

    threats = []
    metadata = {}

    try:
        with open(con_image_path, "rb") as f:
            header = f.read(4)
            # Check magic bytes for spoofing
            if header.startswith(b"<?xml") or b"script" in f.read(1000).lower():
                threats.append("Possible embedded script in header")

        img = pil_image.open(con_image_path)
        format_str = str(img.format or "unknown").upper()
        metadata["format"] = format_str
        metadata["width"] = img.width
        metadata["height"] = img.height
        metadata["mode"] = img.mode
        metadata["file_size_kb"] = os.path.getsize(con_image_path) / 1024

        # Check for suspicious EXIF data
        try:
            exif_data = img._getexif()
            if exif_data:
                metadata["has_exif"] = True
                # Check for GPS data that might leak location
                for tag, value in exif_data.items():
                    if tag in (34853, 34854):  # GPS IFD tags
                        threats.append("GPS location data found in EXIF")
                        break
        except Exception:
            pass

        # Check for anomalies
        if metadata["width"] > 10000 or metadata["height"] > 10000:
            threats.append("Extremely large image dimensions (possible DoS vector)")

    except Exception as e:
        return {"success": False, "error": f"scan_image failed: {e}"}

    result: Dict[str, Any] = {
        "success": True,
        "path": con_image_path,
        "threats": threats,
        "metadata": metadata,
        "threat_level": "high" if threats else "low",
    }

    return result


def audit_image_con(
    con_image_path: str,
    con_quarantine_reason: Optional[str] = None,
    con_project: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Audit and optionally quarantine an image based on threats.
    Move to quarantine folder if con_quarantine_reason provided.

    Args:
        con_image_path        : path to image file to audit
        con_quarantine_reason : if provided, move file to quarantine with this reason
        con_project           : optional, writes NBS audit wrapper

    Returns dict with 'success', 'action', 'quarantine_path'.
    Requires: Pillow (for scan), shutil (built-in)
    """
    # First scan the image
    scan_result = scan_image_con(con_image_path, con_project=None)
    if not scan_result.get("success"):
        return scan_result  # Propagate scan error

    threat_level = scan_result.get("threat_level", "low")
    quarantine_path = None
    action = "audited"

    # If high threat or explicit quarantine reason, move to quarantine
    if con_quarantine_reason or threat_level == "high":
        try:
            quarantine_dir = os.path.join(
                os.path.dirname(con_image_path), "__quarantine__"
            )
            os.makedirs(quarantine_dir, exist_ok=True)
            reason_str = (con_quarantine_reason or threat_level).replace(" ", "_")[:50]
            base_name = os.path.basename(con_image_path)
            name, ext = os.path.splitext(base_name)
            quarantine_path = os.path.join(
                quarantine_dir,
                f"{name}__quarantined__{reason_str}{ext}",
            )
            shutil.move(con_image_path, quarantine_path)
            action = "quarantined"
        except Exception as e:
            return {"success": False, "error": f"Quarantine failed: {e}"}

    result: Dict[str, Any] = {
        "success": True,
        "path": con_image_path,
        "action": action,
        "threat_level": threat_level,
        "threats": scan_result.get("threats", []),
        "metadata": scan_result.get("metadata", {}),
    }

    if quarantine_path:
        result["quarantine_path"] = quarantine_path

    return result


def scan_docx_con(
    con_docx_path: str,
) -> Dict[str, Any]:
    """
    Scan a DOCX file for embedded threats: macros, code, OLE objects, external links.

    Args:
        con_docx_path : path to .docx file to scan

    Returns dict with 'success', 'threats' list, 'metadata'.
    Requires: python-docx, zipfile (built-in)
    """
    if not os.path.exists(con_docx_path):
        return {"success": False, "error": f"File not found: {con_docx_path}"}

    threats = []
    metadata = {}

    try:
        import zipfile

        metadata["file_size_kb"] = os.path.getsize(con_docx_path) / 1024
        metadata["format"] = "docx"

        # DOCX is a ZIP file; scan the internal structure
        with zipfile.ZipFile(con_docx_path, "r") as zf:
            file_list = zf.namelist()
            metadata["internal_files"] = len(file_list)

            # Check for VBA macros (usually in /word/vbaProject.bin or /xl/vbaProject.bin)
            if any("vbaProject" in f for f in file_list):
                threats.append("VBA macros detected (potential malware vector)")

            # Check for embedded objects
            if "word/embeddings/" in str(file_list):
                threats.append("Embedded objects found (potential execution vector)")

            # Check external relationships (links to external servers)
            for fname in file_list:
                if fname.endswith(".rels"):
                    try:
                        content = zf.read(fname).decode("utf-8", errors="ignore")
                        if "http://" in content or "ftp://" in content:
                            threats.append(
                                "External link in relationships (potential data exfiltration)"
                            )
                            break
                    except Exception:
                        pass

            # Check document.xml for suspicious fields
            try:
                if "word/document.xml" in file_list:
                    doc_xml = zf.read("word/document.xml").decode("utf-8", errors="ignore")
                    if "<w:fldCode>" in doc_xml or "EXTERNAL" in doc_xml:
                        threats.append("Dynamic field code detected (potential injection)")
                    if "field_update" in doc_xml.lower():
                        threats.append("Auto-update field detected")
            except Exception:
                pass

    except Exception as e:
        return {"success": False, "error": f"scan_docx failed: {e}"}

    result: Dict[str, Any] = {
        "success": True,
        "path": con_docx_path,
        "threats": threats,
        "metadata": metadata,
        "threat_level": "high" if threats else "low",
    }

    return result


def scan_xlsx_con(
    con_xlsx_path: str,
) -> Dict[str, Any]:
    """
    Scan an XLSX file for threats: formulas, external links, VBA, data validation tricks.

    Args:
        con_xlsx_path : path to .xlsx file to scan

    Returns dict with 'success', 'threats' list, 'metadata'.
    Requires: zipfile (built-in)
    """
    import zipfile

    if not os.path.exists(con_xlsx_path):
        return {"success": False, "error": f"File not found: {con_xlsx_path}"}

    threats = []
    metadata = {}

    try:
        metadata["file_size_kb"] = os.path.getsize(con_xlsx_path) / 1024
        metadata["format"] = "xlsx"

        with zipfile.ZipFile(con_xlsx_path, "r") as zf:
            file_list = zf.namelist()
            metadata["internal_files"] = len(file_list)

            # Check for VBA macros
            if any("vbaProject" in f for f in file_list):
                threats.append("VBA macros detected in XLSX")

            # Check workbook.xml for external connections
            try:
                if "xl/workbook.xml" in file_list:
                    wbk = zf.read("xl/workbook.xml").decode("utf-8", errors="ignore")
                    if "externalLink" in wbk:
                        threats.append("External link references found")
                    if "dataConnection" in wbk:
                        threats.append("Data connection found (potential data exfiltration)")
            except Exception:
                pass

            # Check worksheets for suspicious formulas
            for fname in file_list:
                if fname.startswith("xl/worksheets/sheet") and fname.endswith(".xml"):
                    try:
                        sheet_xml = zf.read(fname).decode("utf-8", errors="ignore")
                        # Check for formula injection patterns
                        if "=cmd|" in sheet_xml or "=powershell" in sheet_xml:
                            threats.append("Command injection formula detected")
                        if "=WEBSERVICE(" in sheet_xml:
                            threats.append("WEBSERVICE formula (data exfil potential)")
                        if "=HYPERLINK(" in sheet_xml and ("http" in sheet_xml or "ftp" in sheet_xml):
                            threats.append("Suspicious hyperlink formula")
                    except Exception:
                        pass

            # Check for data validation with malicious patterns
            try:
                if "xl/dataValidations.xml" in file_list:
                    dv = zf.read("xl/dataValidations.xml").decode("utf-8", errors="ignore")
                    if "prompt" in dv.lower() and ("password" in dv.lower() or "login" in dv.lower()):
                        threats.append("Credential prompt data validation (social engineering)")
            except Exception:
                pass

    except Exception as e:
        return {"success": False, "error": f"scan_xlsx failed: {e}"}

    result: Dict[str, Any] = {
        "success": True,
        "path": con_xlsx_path,
        "threats": threats,
        "metadata": metadata,
        "threat_level": "high" if threats else "low",
    }

    return result


def scan_pdf_con(
    con_pdf_path: str,
) -> Dict[str, Any]:
    """
    Scan a PDF file for threats: embedded scripts, form handlers, unusual objects.

    Args:
        con_pdf_path : path to .pdf file to scan

    Returns dict with 'success', 'threats' list, 'metadata'.
    """
    if not os.path.exists(con_pdf_path):
        return {"success": False, "error": f"File not found: {con_pdf_path}"}

    threats = []
    metadata = {}

    try:
        metadata["file_size_kb"] = os.path.getsize(con_pdf_path) / 1024
        metadata["format"] = "pdf"

        # Read raw PDF to look for suspicious patterns
        with open(con_pdf_path, "rb") as f:
            content = f.read()
            metadata["size_bytes"] = len(content)

            # Check for JavaScript in PDF
            if b"/JavaScript" in content or b"/JS" in content:
                threats.append("JavaScript embedded in PDF (potential exploit)")

            # Check for launch actions (external program execution)
            if b"/Launch" in content or b"/SubmitForm" in content:
                threats.append("Launch/form action detected (potential RCE)")

            # Check for embedded files
            if b"/EmbeddedFile" in content:
                threats.append("Embedded files in PDF (potential malware payload)")

            # Check for OpenAction (auto-execute on open)
            if b"/OpenAction" in content:
                threats.append("OpenAction detected (auto-execute on open)")

            # Check for external references
            if b"/XObject" in content or b"/ObjStm" in content:
                if b"http" in content or b"ftp" in content:
                    threats.append("External resource reference in PDF")

            # Check for form field submit to external URL
            if b"/SubmitForm" in content:
                if b"http" in content or b"ftp" in content:
                    threats.append("Form submission to external URL detected")

            # Check for unusually large compressed streams (potential polyglot/exploit)
            if b"stream" in content:
                stream_count = content.count(b"stream")
                metadata["stream_count"] = stream_count
                if stream_count > 50:
                    threats.append("High number of streams (potential polyglot/exploit)")

    except Exception as e:
        return {"success": False, "error": f"scan_pdf failed: {e}"}

    result: Dict[str, Any] = {
        "success": True,
        "path": con_pdf_path,
        "threats": threats,
        "metadata": metadata,
        "threat_level": "high" if threats else "low",
    }

    return result


def audit_files_con(
    con_file_paths: List[str],
    con_quarantine_on_threat: bool = True,
) -> Dict[str, Any]:
    """
    Batch audit multiple office files (DOCX, XLSX, PDF, images).
    Auto-quarantine if threats detected and con_quarantine_on_threat=True.

    Args:
        con_file_paths         : list of file paths to audit
        con_quarantine_on_threat: if True, quarantine threatened files

    Returns dict with 'success', 'results' list, 'quarantined_count'.
    """
    results = []
    quarantined_count = 0

    for fpath in (con_file_paths or []):
        if not os.path.exists(fpath):
            results.append({"path": fpath, "success": False, "error": "File not found"})
            continue

        ext = os.path.splitext(fpath)[1].lower()
        scan_result = None

        if ext == ".docx":
            scan_result = scan_docx_con(fpath)
        elif ext == ".xlsx":
            scan_result = scan_xlsx_con(fpath)
        elif ext == ".pdf":
            scan_result = scan_pdf_con(fpath)
        elif ext in (".png", ".jpg", ".jpeg", ".gif", ".bmp"):
            scan_result = scan_image_con(fpath)
        else:
            results.append({"path": fpath, "success": False, "error": f"Unsupported format: {ext}"})
            continue

        if not scan_result.get("success"):
            results.append(scan_result)
            continue

        threat_level = scan_result.get("threat_level", "low")
        threats = scan_result.get("threats", [])

        action = "passed"
        quarantine_path = None

        if (threat_level == "high" or threats) and con_quarantine_on_threat:
            try:
                quarantine_dir = os.path.join(os.path.dirname(fpath), "__quarantine__")
                os.makedirs(quarantine_dir, exist_ok=True)
                threat_str = (threats[0] if threats else "high_threat").replace(" ", "_")[:40]
                base_name = os.path.basename(fpath)
                name, ext_part = os.path.splitext(base_name)
                quarantine_path = os.path.join(
                    quarantine_dir, f"{name}__quarantined__{threat_str}{ext_part}"
                )
                shutil.move(fpath, quarantine_path)
                action = "quarantined"
                quarantined_count += 1
            except Exception as e:
                results.append(
                    {"path": fpath, "success": False, "error": f"Quarantine failed: {e}"}
                )
                continue

        result_entry = {
            "path": fpath,
            "success": True,
            "threat_level": threat_level,
            "threats": threats,
            "action": action,
        }
        if quarantine_path:
            result_entry["quarantine_path"] = quarantine_path

        results.append(result_entry)

    return {
        "success": True,
        "results": results,
        "quarantined_count": quarantined_count,
        "total_audited": len(con_file_paths or []),
    }


__all__ = [
    "king_sovereignty_check",
    "paladin_gate",
    "sheriff_audit",
    "run_security_harness_check",
    "dispatch_security",
    "scout_house_posture_sec",
    "evaluate_sovereignty_sec",
    "security_vault_lifecycle_sec",
    "security_incident_lifecycle_sec",
    "safe_zeroize_sec",
    "stables_init_session_sec",
    "stables_validate_session_sec",
    "stables_mark_session_drop_sec",
    "stables_close_session_sec",
    "validate_ami_id_sec",
    "validate_amip_payload_sec",
    "validate_bucey_shunt_sec",
    "validate_mail_transport_sec",
    "audit_amip_event_sec",
    "scan_image_con",
    "audit_image_con",
    "scan_docx_con",
    "scan_xlsx_con",
    "scan_pdf_con",
    "audit_files_con",
]


# --- Artifact JSON writers (result.meta.json, distant_end.json, master_result.json) ---
def _write_security_artifacts(status: str, reached: bool, reason: str) -> None:
    """Write/update the three pillar artifact JSON files for SECURITY."""
    _here = os.path.dirname(os.path.abspath(__file__))
    _local = {
        "pillar": "sara_security",
        "file": "sara_securitygen1.py",
        "status": status,
        "reached": reached,
        "reason": reason,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    _distant = {
        "pillar": "sara_security",
        "file": "sara_securitygen1.py",
        "status": status,
        "reached": reached,
        "note": reason,
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    _master = {"pillar": "sara_security", "final_status": status, "local": _local, "distant": _distant}
    for fname, obj in [("result.meta.json", _local), ("distant_end.json", _distant), ("master_result.json", _master)]:
        try:
            with open(os.path.join(_here, fname), "w", encoding="utf-8") as f:
                json.dump(obj, f, ensure_ascii=False, indent=2)
        except Exception:
            pass


